version: "3.5"

services:
  app:
    container_name: app
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    image: mysql:8.0.23
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    env_file:
      - .env

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.1.0/24

volumes:
  mysql-data:
